name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - run: composer install --prefer-dist --no-progress
        working-directory: wp-betterforms
      - run: vendor/bin/phpunit
        working-directory: wp-betterforms
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
        working-directory: wp-betterforms
      - run: npm run build
        working-directory: wp-betterforms
      - run: npm test
        working-directory: wp-betterforms
